### ISSUE TITLE
Accordion block improvement - Use one title

### ISSUE THREAD

**Issue by anuj-adobe** [aemsites/infosys#33]
There are two parts in accordion block - 
1) itemTitle: It show up when accordion item is collapsed
2) itemContent: It show up when accordion item is expanded

In existing implementation of accordion block, 'H4' heading is expected in itemTitle row and 'H3' heading is expected in itemContent while authoring.

**Objective:** Avoid the requirement to add same heading at two places.

For example -
In following image, even if "Infosys Techcompass" is removed from the second column (inner column data) the title should display there by picking it from the row above it.
![image](https://github.com/aemsites/infosys/assets/66720268/4322dce4-2496-4cd1-8015-48e4aa345a81)

**Improvement**

Modified authoring doc like this -
<img width="729" alt="image" src="https://github.com/aemsites/infosys/assets/66720268/a18d34a1-7fd5-4512-a9b1-06c16fe5044f">

- Author can show same heading and only need to add 'H4' text in the row.
- Author can show different headings if he adds 'H4' in the row and 'H3' in the column inner data.

**Comment by shrotia** [comment]
Yes looks good. 

> Author can show different headings if he adds 'H4' in the row and 'H3' in the column inner data.

IMHO let't not mention it anywhere (Block Library/ Word documents) until it is coming from the field. Let it be there in the code if it is already implemented.
