### ISSUE TITLE
[Internal QA] Header Look & Feel improvements

### ISSUE THREAD

**Issue by anuj-adobe** [aemsites/infosys#74]
**Desktop Original**
<img width="1790" alt="image" src="https://github.com/aemsites/infosys/assets/66720268/26dbae77-a0bc-487a-a68c-29079cea583a">

**Desktop EDS**
<img width="1792" alt="image" src="https://github.com/aemsites/infosys/assets/66720268/feb93255-9bcf-4e92-a03c-ff7b609c7162">

**Mobile Original**
<img width="496" alt="image" src="https://github.com/aemsites/infosys/assets/66720268/06681d56-11c8-4117-b3b2-a7c29ceb2f2e">

<img width="502" alt="image" src="https://github.com/aemsites/infosys/assets/66720268/82bab61f-4f0a-4903-b549-2e9b861fa5b9">

<img width="500" alt="image" src="https://github.com/aemsites/infosys/assets/66720268/71b8327a-9e9b-4c1d-926e-bc93d01856ed">

**Mobile EDS**
<img width="500" alt="image" src="https://github.com/aemsites/infosys/assets/66720268/414dfea0-7267-4321-90a1-d88e88e77942">

<img width="501" alt="image" src="https://github.com/aemsites/infosys/assets/66720268/fa686ec7-4b14-4f3c-b650-c35d6ebac037">

<img width="499" alt="image" src="https://github.com/aemsites/infosys/assets/66720268/f4e85ff7-b1e7-4c26-b1f0-f0c50ea8f584">

**Comment by anuj-adobe** [comment]
Bugs -

| # | Bug | Mode |
|--|------|------|
| 1 | Header is slightly mis-aligned from other sections. It seems padding is missing from it| Desktop |
| 2 | Navigation items list is leftward aligned compared to original header | Desktop |
| 3 | Search Icon color is darker compared to original header icon | Desktop |
| 4 | Navigation items font is bigger compared to original header | Desktop |
| 5 | Share icon also seems bigger and different in color compared to original | Desktop |

**Comment by shrotia** [comment]
Fixed the fonts weights, sizing and alignment issue of the logo. 

https://github.com/aemsites/infosys/assets/119420493/c79fbdbf-4581-4e80-aec5-50388982f7a2
